/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicDepositCallbackRouteImport } from './routes/api/public/deposit-callback'
import { Route as ApiPublicBinBinRouteImport } from './routes/api/public/bin.$bin'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDepositCallbackRoute =
  ApiPublicDepositCallbackRouteImport.update({
    id: '/api/public/deposit-callback',
    path: '/api/public/deposit-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBinBinRoute = ApiPublicBinBinRouteImport.update({
  id: '/api/public/bin/$bin',
  path: '/api/public/bin/$bin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/public/deposit-callback': typeof ApiPublicDepositCallbackRoute
  '/api/public/bin/$bin': typeof ApiPublicBinBinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/public/deposit-callback': typeof ApiPublicDepositCallbackRoute
  '/api/public/bin/$bin': typeof ApiPublicBinBinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/public/deposit-callback': typeof ApiPublicDepositCallbackRoute
  '/api/public/bin/$bin': typeof ApiPublicBinBinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/api/public/deposit-callback'
    | '/api/public/bin/$bin'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$' | '/api/public/deposit-callback' | '/api/public/bin/$bin'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/api/public/deposit-callback'
    | '/api/public/bin/$bin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ApiPublicDepositCallbackRoute: typeof ApiPublicDepositCallbackRoute
  ApiPublicBinBinRoute: typeof ApiPublicBinBinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/deposit-callback': {
      id: '/api/public/deposit-callback'
      path: '/api/public/deposit-callback'
      fullPath: '/api/public/deposit-callback'
      preLoaderRoute: typeof ApiPublicDepositCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bin/$bin': {
      id: '/api/public/bin/$bin'
      path: '/api/public/bin/$bin'
      fullPath: '/api/public/bin/$bin'
      preLoaderRoute: typeof ApiPublicBinBinRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ApiPublicDepositCallbackRoute: ApiPublicDepositCallbackRoute,
  ApiPublicBinBinRoute: ApiPublicBinBinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
